services:
  slavna_bot:
    container_name: slavna_bot
    build: .
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./data:/app/data
      - ./secrets:/app/secrets
    restart: unless-stopped
